
# SEO settings
title: "Meni"
title2: "" # default: ""
description: "Description"
keywords: "Jekyll, code"
url: http://shmeni.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Meni Orenbach"
  job      : "Security researcher. Always looking for new challenges"
  bio      : "I also like to trek, cycle, run and swim when I get the chance."
  email    : ""
  url      : http://shmeni.github.io
  github   : http://github.com/shmeni

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : projects
    title: Projects
  - slug : publications
    title: Publications

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
